// Generated by LiveScript 1.4.0
(function(){
  var ffi, libc, exports;
  ffi = require('ffi');
  libc = new ffi.Library('libc', {
    'system': ['int32', ['string']]
  });
  module.exports = exports = libc.system;
}).call(this);
